#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.
# https://github.com/github/scripts-to-rule-them-all

set -e

cd "$(dirname "$0")/.."

echo "==> Running tests..."
date "+%H:%M:%S"

script/test

date "+%H:%M:%S"
